packages:
  - "apps/*"
  - "packages/*"

injectWorkspacePackages: true

allowBuilds:
  argon2: true
  esbuild: true
  "@parcel/watcher": true
  "@prisma/engine": true
  prisma: true
  "nestjs/core": false
  "@prisma/engines": true
  "@scarf/scarf": false
  unrs-resolver: false
